apiVersion: v1
kind: ConfigMap
metadata:
  name: python-web-app-config
data:
  APP_ENV: production
  LOG_LEVEL: debug

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-web-app

spec:
  replicas: 6
  
  selector:
    matchLabels:
      app: python-web-app

  template:
    metadata:
      labels:
        app: python-web-app 
  
    spec:
      containers:
        - name: python-web-app
          image: cocomiyati/docker-basic-web-app:latest
          ports:
            - containerPort: 5000
          readinessProbe: 
            httpGet:
              path: /
              port: 5000
            initalDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: python-web-app-secret
                  key: DB_PASSWORD

            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: python-web-app-secret
                  key: API_TOKEN

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: python-web-app-config
                  key: APP_ENV

            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: python-web-app-config
                  key: LOG_LEVEL

---
apiVersion: v1
kind: Service

metadata:
  name: python-web-app-service

spec:
  type: NodePort

  selector:
    app: python-web-app

  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: python-web-app-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-web-app

  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70